server:
  port: 8888

spring:
  application:
    name: config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/insectwood/micro-service-application
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
