server:
  port: 8888

spring:
  application:
    name: config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/IdeaProjects/msa/msa-config
        git:
          uri: https://github.com/insectwood/micro-service-application/msa-config
          #username: username
          #password: password

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
