server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter

      routes:
        - id: application-user
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/application-user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/application-user/(?<segment>.*), /$\{segment}
        - id: application-user
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/application-user/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/application-user/(?<segment>.*), /$\{segment}
        - id: application-user
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/application-user/**
             - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/application-user/(?<segment>.*), /$\{segment}

        - id: application-catalog
          uri: lb://APPLICATION-CATALOG
          predicates:
            - Path=/application-catalog/**
        - id: application-order
          uri: lb://APPLICATION-ORDER
          predicates:
            - Path=/application-order/**
          filters:
            - CustomFilter

        - id: application-user
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/application-user/actuator**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/application-user/(?<segment>.*), /$\{segment}

        - id: application-order
          uri: lb://APPLICATION-ORDER
          predicates:
            - Path=/application-order/actuator**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/application-order/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus
